### ISSUE TITLE
Functions called twice within tests when calling pytest (not using line profiling)

### ISSUE THREAD

**Issue by sjrl** [mgaitan/pytest-line-profiler#1]
I noticed that when I have this package installed that each line in my tests are executed twice. For example

```
def test_simple():
    print("Hello")
    return 1
```

If I run the above test using `pytest -k test_simple -s`, I notice that "Hello" is printed twice. When I only have `pytest` installed then I get the expected behavior of "Hello" is printed once.

**Comment by theRealSuperMario** [comment]
Yes, same problem here. Apart from that, this package is sick 🚀
